title:  <center>Rachel Yap</center> 

logo: "/images/Avatar circle.png"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/">LinkedIn</a> |
  <a href="https://github.com/rachelyye">GitHub</a>
  </p>
  
  <p align="justify">
  On a challenge to build a data analyst portfolio.
  <br><br>
  </p>
  
  github: is\_project\_page:false
  
theme: jekyll-theme-minimal
google_analytics: xxxxxx # Google Analytics tracking ID
