title: <center>Rachel Yap</center> # your name (or website title) here
logo: "/images/Avatar circle.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  On a challenge to build a data analyst portfolio
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
